#!/bin/sh -e
# the enviroment vavules for DAQ module
export PROJECT=daq-module
export PRJROOT=/home/miku/private_repository/my_private_repository/control-project/${PROJECT} 
export TARGET=powerpc-unknown-linux
export HOST=i686-cross-linux-gnu
export PREFIX=${PRJROOT}/tools
export TARGET_PREFIX=${PREFIX}/${TARGET}
export PATH=${PREFIX}/bin:${PATH}
cd ${PRJROOT}
